advdepth: 16
batch_norm: false
batch_size: 64
colors: 1
dataset: MNIST
depth: 16
device: cuda:3
epochs: 101
eval_each: 10
gamma: 0.2
latent: 2
latent_width: 4
lmbda: 0.5
log_dir: 4DatasetAE/MNIST_latent2_BN/
lr: 0.0001
n_classes: 10
weight_decay: 1.0e-05
width: 32
