advdepth: 64
batch_norm: false
batch_size: 64
colors: 3
dataset: SVHN
depth: 64
device: cuda:3
epochs: 101
eval_each: 10
gamma: 0.2
latent: 16
latent_width: 4
lmbda: 0.5
log_dir: 4DatasetAE/SVHN_latent16/
lr: 0.0001
n_classes: 10
weight_decay: 1.0e-05
width: 32
